Repository petrucioata/codecraft-info, pull requests merged in 2019-07, with the labels that each got.

#3 ParticipantsController and corresponding views
  app/assets/javascripts/participants.coffee
  app/assets/stylesheets/participants.scss
  app/controllers/participants_controller.rb
  app/helpers/participants_helper.rb
  app/views/participants/_form.html.erb
  app/views/participants/edit.html.erb
  app/views/participants/index.html.erb
  app/views/participants/new.html.erb
  app/views/participants/show.html.erb
  config/routes.rb
  spec/factories/participant.rb
  spec/factories/position.rb
  spec/helpers/participants_helper_spec.rb
  spec/requests/participant_spec.rb
Labels: enhancement

#4 Update editions specs/MVC
  app/controllers/editions_controller.rb
  app/models/edition.rb
  app/views/editions/edit.html.erb
  app/views/editions/new.html.erb
  app/views/editions/show.html.erb
  spec/factories/edition.rb
  spec/models/edition_spec.rb
  spec/requests/edition_spec.rb
Labels: improvement

#5 Add Rubocop & Guard gems
  .rubocop.yml
  Gemfile
  Gemfile.lock
  Guardfile
  README.md
  Rakefile
  app/channels/application_cable/channel.rb
  app/channels/application_cable/connection.rb
  app/controllers/application_controller.rb
  app/controllers/editions_controller.rb
  app/controllers/participants_controller.rb
  app/helpers/application_helper.rb
  app/helpers/editions_helper.rb
  app/helpers/participants_helper.rb
  app/jobs/application_job.rb
  app/mailers/application_mailer.rb
  app/models/application_record.rb
  app/models/edition.rb
  app/models/participant.rb
  app/models/participation.rb
  app/models/position.rb
  app/models/solution.rb
  app/models/task.rb
  app/views/editions/index.html.erb
  config.ru
  spec/factories/edition.rb
  spec/factories/participant.rb
  spec/factories/position.rb
  spec/helpers/application_helper_spec.rb
  spec/helpers/editions_helper_spec.rb
  spec/helpers/participants_helper_spec.rb
  spec/models/participant_spec.rb
  spec/models/participation_spec.rb
  spec/models/position_spec.rb
  spec/models/solution_spec.rb
  spec/models/task_spec.rb
  spec/rails_helper.rb
  spec/requests/edition_spec.rb
  spec/requests/participant_spec.rb
  spec/spec_helper.rb
  spec/support/factory_bot.rb
  spec/views/editions/index.html.erb_spec.rb
  test/application_system_test_case.rb
  test/controllers/.keep
  test/fixtures/.keep
  test/fixtures/files/.keep
  test/helpers/.keep
  test/integration/.keep
  test/mailers/.keep
  test/models/.keep
  test/system/.keep
  test/test_helper.rb
Labels: documentation, improvement

#6 Set optional:true for 1:M relationships for Task-Edition and Participant-Position
  app/models/participant.rb
  app/models/task.rb
  app/views/participants/index.html.erb
  spec/models/participant_spec.rb
Labels: bug

#8 Small but important bug fixes
  app/models/solution.rb
  app/views/participants/_form.html.erb
Labels: bug

#7 Task 31161
  app/assets/javascripts/tasks.coffee
  app/assets/stylesheets/tasks.scss
  app/controllers/tasks_controller.rb
  app/helpers/tasks_helper.rb
  app/models/task.rb
  app/views/tasks/_form.html.erb
  app/views/tasks/edit.html.erb
  app/views/tasks/index.html.erb
  app/views/tasks/new.html.erb
  app/views/tasks/show.html.erb
  config/routes.rb
  spec/factories/task.rb
  spec/helpers/tasks_helper_spec.rb
  spec/requests/task_spec.rb
Labels: enhancement

#9 Task 31269
  Gemfile
  Gemfile.lock
  app/assets/javascripts/application.js
  app/assets/stylesheets/application.css.scss
  app/views/editions/index.html.erb
  app/views/layouts/application.html.erb
  app/views/partials/_navbar.html.erb
  app/views/participants/index.html.erb
  app/views/tasks/_form.html.erb
  app/views/tasks/index.html.erb
Labels: enhancement

#10 T 31231 - Import CSV file
  app/controllers/editions_controller.rb
  app/models/edition.rb
  app/views/editions/index.html.erb
  app/views/editions/new_import.html.erb
  app/views/editions/show.html.erb
  app/views/participants/show.html.erb
  config/routes.rb
  spec/fixtures/malformatted.csv
  spec/fixtures/well_formatted.csv
  spec/models/edition_spec.rb
  spec/requests/edition_spec.rb
Labels: enhancement

#11 Task 31258
  Gemfile
  Gemfile.lock
  app/controllers/editions_controller.rb
  app/controllers/participants_controller.rb
  app/controllers/tasks_controller.rb
  app/views/editions/index.html.erb
  app/views/editions/show.html.erb
  app/views/participants/index.html.erb
  app/views/participants/show.html.erb
  app/views/tasks/index.html.erb
  config/initializers/will_paginate.rb
Labels: enhancement

#12 Task 31286
  app/assets/stylesheets/application.css.scss
  app/controllers/application_controller.rb
  app/controllers/editions_controller.rb
  app/controllers/participants_controller.rb
  app/controllers/tasks_controller.rb
  app/helpers/application_helper.rb
  app/models/participant.rb
  app/views/editions/_form.html.erb
  app/views/editions/edit.html.erb
  app/views/editions/index.html.erb
  app/views/editions/new.html.erb
  app/views/editions/show.html.erb
  app/views/partials/_alerts.html.erb
  app/views/partials/_navbar.html.erb
  app/views/participants/_form.html.erb
  app/views/participants/edit.html.erb
  app/views/participants/index.html.erb
  app/views/participants/new.html.erb
  app/views/participants/show.html.erb
  app/views/tasks/_form.html.erb
  app/views/tasks/edit.html.erb
  app/views/tasks/index.html.erb
  app/views/tasks/new.html.erb
  app/views/tasks/show.html.erb
Labels: enhancement

#13 [fe_fixes] add datepicker
  app/assets/stylesheets/application.css.scss
  app/controllers/editions_controller.rb
  app/views/editions/_form.html.erb
  app/views/editions/new_import.html.erb
Labels: enhancement

#14 Spec fix
  spec/requests/edition_spec.rb
Labels: bug

#15 Task 31287
  .gitignore
  README.md
  app/controllers/tasks_controller.rb
  app/models/task.rb
  app/views/tasks/_form.html.erb
  app/views/tasks/show.html.erb
  config/samples/storage.yml
  db/migrate/20190708123006_create_active_storage_tables.active_storage.rb
  db/schema.rb
  spec/fixtures/test_case.txt
  spec/requests/task_spec.rb
Labels: enhancement

#16 Task 31289
  Gemfile
  Gemfile.lock
  app/assets/javascripts/sessions.coffee
  app/assets/stylesheets/sessions.scss
  app/controllers/application_controller.rb
  app/controllers/editions_controller.rb
  app/controllers/participants_controller.rb
  app/controllers/sessions_controller.rb
  app/controllers/tasks_controller.rb
  app/helpers/sessions_helper.rb
  app/models/user.rb
  app/views/editions/index.html.erb
  app/views/editions/show.html.erb
  app/views/partials/_navbar.html.erb
  app/views/participants/index.html.erb
  app/views/participants/show.html.erb
  app/views/sessions/new.html.erb
  app/views/tasks/index.html.erb
  app/views/tasks/show.html.erb
  config/routes.rb
  db/migrate/20190709115827_create_users.rb
  db/schema.rb
  spec/factories/users.rb
  spec/helpers/sessions_helper_spec.rb
  spec/models/user_spec.rb
  spec/request_spec_helpers.rb
  spec/requests/edition_spec.rb
  spec/requests/participant_spec.rb
  spec/requests/session_spec.rb
  spec/requests/task_spec.rb
  spec/spec_helper.rb
Labels: enhancement

#17 Task 31369
  app/assets/javascripts/dashboard.coffee
  app/assets/stylesheets/dashboard.scss
  app/controllers/dashboard_controller.rb
  app/helpers/dashboard_helper.rb
  app/models/participation.rb
  app/views/charts/_simple_column.html.erb
  app/views/charts/_simple_pie.html.erb
  app/views/charts/_stacked_area.html.erb
  app/views/dashboard/index.html.erb
  app/views/layouts/application.html.erb
  config/routes.rb
  spec/factories/edition.rb
  spec/helpers/dashboard_helper_spec.rb
  spec/requests/dashboard_spec.rb
Labels: enhancement

#19 UI changes
  app/helpers/application_helper.rb
  app/models/edition.rb
  app/views/editions/index.html.erb
  app/views/editions/show.html.erb
  app/views/partials/_navbar.html.erb
  app/views/tasks/index.html.erb
Labels: improvement

#18 TASK 31493 - Search functionality for participants
  app/controllers/participants_controller.rb
  app/models/participant.rb
  app/views/partials/_search_form.html.erb
  app/views/participants/index.html.erb
  app/views/tasks/index.html.erb
Labels: enhancement, wip
