Repository petrucioata/codecraft-info, pull requests merged in 2020-10, with the labels that each got.

#44 Task 41091
  app/controllers/dashboard_controller.rb
  app/controllers/editions_controller.rb
  app/controllers/participants_controller.rb
  app/controllers/tasks_controller.rb
  app/models/edition.rb
  app/models/participant.rb
  app/models/participation.rb
  app/models/position.rb
  app/models/solution.rb
  app/models/task.rb
  app/models/user.rb
  app/views/participants/_form.html.erb
  app/views/tasks/_form.html.erb
  db/migrate/20190620192051_create_positions.rb
  db/migrate/20190622163202_create_editions.rb
  db/migrate/20190622163837_create_participants.rb
  db/migrate/20190622171504_create_participations.rb
  db/migrate/20190622174419_create_tasks.rb
  db/migrate/20190622190707_create_solutions.rb
  db/migrate/20190709115827_create_users.rb
  db/schema.rb
  spec/requests/edition_spec.rb
  spec/requests/participant_spec.rb
  spec/requests/task_spec.rb
Labels: improvement

#46 Task 41262
  Gemfile
  Gemfile.lock
  app/controllers/participants_controller.rb
  app/controllers/tasks_controller.rb
  app/models/participant.rb
  app/models/task.rb
  config/environments/development.rb
  config/environments/test.rb
  spec/spec_helper.rb
Labels: bug, enhancement

#47 Task 41263
  .rubocop.yml
  app/models/edition.rb
  spec/factories/edition.rb
  spec/models/edition_spec.rb
Labels: improvement

#45 Task #41092
  app/models/user.rb
Labels: improvement

#48 Task 41317
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/helpers/dashboard_helper.rb
  app/helpers/editions_helper.rb
  app/helpers/participants_helper.rb
  app/helpers/sessions_helper.rb
  app/models/edition.rb
  spec/factories/solution.rb
  spec/helpers/dashboard_helper_spec.rb
  spec/helpers/editions_helper_spec.rb
  spec/helpers/participants_helper_spec.rb
  spec/helpers/sessions_helper_spec.rb
  spec/helpers/tasks_helper_spec.rb
  spec/models/edition_spec.rb
  spec/models/participant_spec.rb
  spec/models/participation_spec.rb
  spec/models/position_spec.rb
  spec/models/solution_spec.rb
  spec/models/task_spec.rb
  spec/models/user_spec.rb
  spec/rails_helper.rb
  spec/requests/edition_spec.rb
  spec/requests/participant_spec.rb
  spec/requests/session_spec.rb
  spec/requests/task_spec.rb
  spec/routes/route_spec.rb
Labels: enhancement

#51 Task 41484
  app/controllers/dashboard_controller.rb
  app/controllers/participants_controller.rb
  app/helpers/tasks_helper.rb
  app/models/edition.rb
  app/models/participation.rb
  app/views/charts/_simple_pie.html.erb
  app/views/editions/index.html.erb
  db/migrate/20201021123142_add_participations_count_to_editions.rb
  db/positions.csv
  db/schema.rb
  spec/factories/edition.rb
  spec/factories/participation.rb
  spec/requests/dashboard_spec.rb
Labels: improvement

#50 Task 41482
  app/controllers/participants_controller.rb
  app/models/participation.rb
  app/views/participants/_form.html.erb
  app/views/participants/edit.html.erb
  app/views/participants/show.html.erb
Labels: enhancement

#52 Task 41506
  .gitignore
  app/assets/stylesheets/application.css.scss
  app/controllers/dashboard_controller.rb
  app/models/edition.rb
  app/models/participation.rb
  app/views/dashboard/index.html.erb
  app/views/partials/_places_table.html.erb
  spec/requests/dashboard_spec.rb
Labels: enhancement, improvement
